# Generated by Django 4.0.1
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The total amount of the order at the time of creation.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who placed the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the script.', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the script.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the script. Set to 0 for a free script.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('video_url', models.URLField(blank=True, help_text='URL to a demonstration video (e.g., YouTube).', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this script is visible in the catalog.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='The price of the script at the time the order was placed.', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scripts.order')),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='scripts.script')),
            ],
            options={
                'unique_together': {('order', 'script')},
            },
        ),
    ]
